-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "types.anchored_inferrable"

---@class (exact) anchored_inferrable: RecordValue
anchored_inferrable = {}

---@return Anchor
---@return unanchored_inferrable
function anchored_inferrable:unwrap_anchored_inferrable() end

-- TODO: constructor annotation
---@class (exact) anchored_inferrableType: RecordType
---@field define_record fun(self: anchored_inferrableType, kind: string, params_with_types: ParamsWithTypes): anchored_inferrableType
return {}
