-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "types.binding"

---@class (exact) binding: EnumValue
binding = {}

---@return boolean
function binding:is_let() end
---@return string name
---@return anchored_inferrable expr
function binding:unwrap_let() end
---@return boolean
---@return string name
---@return anchored_inferrable expr
function binding:as_let() end
---@return boolean
function binding:is_tuple_elim() end
---@return ArrayValue names
---@return anchored_inferrable subject
function binding:unwrap_tuple_elim() end
---@return boolean
---@return ArrayValue names
---@return anchored_inferrable subject
function binding:as_tuple_elim() end
---@return boolean
function binding:is_annotated_lambda() end
---@return string param_name
---@return anchored_inferrable param_annotation
---@return Anchor start_anchor
---@return visibility visible
---@return checkable pure
function binding:unwrap_annotated_lambda() end
---@return boolean
---@return string param_name
---@return anchored_inferrable param_annotation
---@return Anchor start_anchor
---@return visibility visible
---@return checkable pure
function binding:as_annotated_lambda() end
---@return boolean
function binding:is_program_sequence() end
---@return anchored_inferrable first
---@return Anchor start_anchor
function binding:unwrap_program_sequence() end
---@return boolean
---@return anchored_inferrable first
---@return Anchor start_anchor
function binding:as_program_sequence() end

---@class (exact) bindingType: EnumType
---@field define_enum fun(self: bindingType, name: string, variants: Variants): bindingType
---@field let fun(name: string, expr: anchored_inferrable): binding
---@field tuple_elim fun(names: ArrayValue, subject: anchored_inferrable): binding
---@field annotated_lambda fun(param_name: string, param_annotation: anchored_inferrable, start_anchor: Anchor, visible: visibility, pure: checkable): binding
---@field program_sequence fun(first: anchored_inferrable, start_anchor: Anchor): binding
return {}
