-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "block_purity.lua"
---@class (exact) block_purity
---@field kind string
---@field pretty_print fun(...)
block_purity = {}
---@return boolean
function block_purity:is_effectful() end
---@return boolean
function block_purity:is_pure() end
---@return boolean
function block_purity:is_dependent() end
---@return value
function block_purity:unwrap_dependent() end
---@return boolean, value
function block_purity:as_dependent() end
---@return boolean
function block_purity:is_inherit() end
---@class (exact) block_purityType:Type
---@field effectful block_purity
---@field pure block_purity
---@field dependent fun(val:value): block_purity
---@field inherit block_purity
return {}
