-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "types.constraintelem"

---@class (exact) constraintelem: EnumValue
constraintelem = {}

---@return boolean
function constraintelem:is_sliced_constrain() end
---@return SubtypeRelation rel
---@return typed right
---@return TypecheckingContext rightctx
---@return any cause
function constraintelem:unwrap_sliced_constrain() end
---@return boolean
---@return SubtypeRelation rel
---@return typed right
---@return TypecheckingContext rightctx
---@return any cause
function constraintelem:as_sliced_constrain() end
---@return boolean
function constraintelem:is_constrain_sliced() end
---@return typed left
---@return TypecheckingContext leftctx
---@return SubtypeRelation rel
---@return any cause
function constraintelem:unwrap_constrain_sliced() end
---@return boolean
---@return typed left
---@return TypecheckingContext leftctx
---@return SubtypeRelation rel
---@return any cause
function constraintelem:as_constrain_sliced() end
---@return boolean
function constraintelem:is_sliced_leftcall() end
---@return typed arg
---@return SubtypeRelation rel
---@return typed right
---@return TypecheckingContext rightctx
---@return any cause
function constraintelem:unwrap_sliced_leftcall() end
---@return boolean
---@return typed arg
---@return SubtypeRelation rel
---@return typed right
---@return TypecheckingContext rightctx
---@return any cause
function constraintelem:as_sliced_leftcall() end
---@return boolean
function constraintelem:is_leftcall_sliced() end
---@return typed left
---@return TypecheckingContext leftctx
---@return typed arg
---@return SubtypeRelation rel
---@return any cause
function constraintelem:unwrap_leftcall_sliced() end
---@return boolean
---@return typed left
---@return TypecheckingContext leftctx
---@return typed arg
---@return SubtypeRelation rel
---@return any cause
function constraintelem:as_leftcall_sliced() end
---@return boolean
function constraintelem:is_sliced_rightcall() end
---@return SubtypeRelation rel
---@return typed right
---@return TypecheckingContext rightctx
---@return typed arg
---@return any cause
function constraintelem:unwrap_sliced_rightcall() end
---@return boolean
---@return SubtypeRelation rel
---@return typed right
---@return TypecheckingContext rightctx
---@return typed arg
---@return any cause
function constraintelem:as_sliced_rightcall() end
---@return boolean
function constraintelem:is_rightcall_sliced() end
---@return typed left
---@return TypecheckingContext leftctx
---@return SubtypeRelation rel
---@return typed arg
---@return any cause
function constraintelem:unwrap_rightcall_sliced() end
---@return boolean
---@return typed left
---@return TypecheckingContext leftctx
---@return SubtypeRelation rel
---@return typed arg
---@return any cause
function constraintelem:as_rightcall_sliced() end

---@class (exact) constraintelemType: EnumType
---@field define_enum fun(self: constraintelemType, name: string, variants: Variants): constraintelemType
---@field sliced_constrain fun(rel: SubtypeRelation, right: typed, rightctx: TypecheckingContext, cause: any): constraintelem
---@field constrain_sliced fun(left: typed, leftctx: TypecheckingContext, rel: SubtypeRelation, cause: any): constraintelem
---@field sliced_leftcall fun(arg: typed, rel: SubtypeRelation, right: typed, rightctx: TypecheckingContext, cause: any): constraintelem
---@field leftcall_sliced fun(left: typed, leftctx: TypecheckingContext, arg: typed, rel: SubtypeRelation, cause: any): constraintelem
---@field sliced_rightcall fun(rel: SubtypeRelation, right: typed, rightctx: TypecheckingContext, arg: typed, cause: any): constraintelem
---@field rightcall_sliced fun(left: typed, leftctx: TypecheckingContext, rel: SubtypeRelation, arg: typed, cause: any): constraintelem
return {}
