-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "types.constraintcause"

---@class (exact) constraintcause: EnumValue
constraintcause = {}

---@return boolean
function constraintcause:is_primitive() end
---@return string description
---@return Anchor position
---@return any track
function constraintcause:unwrap_primitive() end
---@return boolean
---@return string description
---@return Anchor position
---@return any track
function constraintcause:as_primitive() end
---@return boolean
function constraintcause:is_composition() end
---@return integer left
---@return integer right
---@return Anchor position
function constraintcause:unwrap_composition() end
---@return boolean
---@return integer left
---@return integer right
---@return Anchor position
function constraintcause:as_composition() end
---@return boolean
function constraintcause:is_nested() end
---@return string description
---@return constraintcause inner
function constraintcause:unwrap_nested() end
---@return boolean
---@return string description
---@return constraintcause inner
function constraintcause:as_nested() end
---@return boolean
function constraintcause:is_leftcall_discharge() end
---@return integer call
---@return integer constraint
---@return Anchor position
function constraintcause:unwrap_leftcall_discharge() end
---@return boolean
---@return integer call
---@return integer constraint
---@return Anchor position
function constraintcause:as_leftcall_discharge() end
---@return boolean
function constraintcause:is_rightcall_discharge() end
---@return integer constraint
---@return integer call
---@return Anchor position
function constraintcause:unwrap_rightcall_discharge() end
---@return boolean
---@return integer constraint
---@return integer call
---@return Anchor position
function constraintcause:as_rightcall_discharge() end
---@return boolean
function constraintcause:is_lost() end
---@return string unique_string
---@return string stacktrace
---@return any auxiliary
function constraintcause:unwrap_lost() end
---@return boolean
---@return string unique_string
---@return string stacktrace
---@return any auxiliary
function constraintcause:as_lost() end

---@class (exact) constraintcauseType: EnumType
---@field define_enum fun(self: constraintcauseType, name: string, variants: Variants): constraintcauseType
---@field primitive fun(description: string, position: Anchor, track: any): constraintcause
---@field composition fun(left: integer, right: integer, position: Anchor): constraintcause
---@field nested fun(description: string, inner: constraintcause): constraintcause
---@field leftcall_discharge fun(call: integer, constraint: integer, position: Anchor): constraintcause
---@field rightcall_discharge fun(constraint: integer, call: integer, position: Anchor): constraintcause
---@field lost fun(unique_string: string, stacktrace: string, auxiliary: any): constraintcause
return {}
