-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "types.constraintcause"

---@class (exact) constraintcause: EnumValue
constraintcause = {}

---@return boolean
function constraintcause:is_primitive() end
---@return string description
---@return Anchor position
function constraintcause:unwrap_primitive() end
---@return boolean
---@return string description
---@return Anchor position
function constraintcause:as_primitive() end
---@return boolean
function constraintcause:is_composition() end
---@return constraintcause left
---@return constraintcause right
---@return Anchor position
function constraintcause:unwrap_composition() end
---@return boolean
---@return constraintcause left
---@return constraintcause right
---@return Anchor position
function constraintcause:as_composition() end
---@return boolean
function constraintcause:is_leftcall_discharge() end
---@return constraintcause call
---@return constraintcause constraint
---@return Anchor position
function constraintcause:unwrap_leftcall_discharge() end
---@return boolean
---@return constraintcause call
---@return constraintcause constraint
---@return Anchor position
function constraintcause:as_leftcall_discharge() end
---@return boolean
function constraintcause:is_rightcall_discharge() end
---@return constraintcause constraint
---@return constraintcause call
---@return Anchor position
function constraintcause:unwrap_rightcall_discharge() end
---@return boolean
---@return constraintcause constraint
---@return constraintcause call
---@return Anchor position
function constraintcause:as_rightcall_discharge() end
---@return boolean
function constraintcause:is_lost() end
---@return string unique_string
---@return string stacktrace
---@return any auxiliary
function constraintcause:unwrap_lost() end
---@return boolean
---@return string unique_string
---@return string stacktrace
---@return any auxiliary
function constraintcause:as_lost() end

---@class (exact) constraintcauseType: EnumType
---@field define_enum fun(self: constraintcauseType, name: string, variants: Variants): constraintcauseType
---@field primitive fun(description: string, position: Anchor): constraintcause
---@field composition fun(left: constraintcause, right: constraintcause, position: Anchor): constraintcause
---@field leftcall_discharge fun(call: constraintcause, constraint: constraintcause, position: Anchor): constraintcause
---@field rightcall_discharge fun(constraint: constraintcause, call: constraintcause, position: Anchor): constraintcause
---@field lost fun(unique_string: string, stacktrace: string, auxiliary: any): constraintcause
return {}
