-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "continuation.lua"

---@class (exact) continuation: EnumValue
continuation = {}

---@return boolean
function continuation:is_empty() end
---@return nil
function continuation:unwrap_empty() end
---@return boolean
function continuation:as_empty() end
---@return boolean
function continuation:is_frame() end
---@return RuntimeContext, typed
function continuation:unwrap_frame() end
---@return boolean, RuntimeContext, typed
function continuation:as_frame() end
---@return boolean
function continuation:is_sequence() end
---@return continuation, continuation
function continuation:unwrap_sequence() end
---@return boolean, continuation, continuation
function continuation:as_sequence() end

---@class (exact) continuationType: EnumType
---@field empty continuation
---@field frame fun(context: RuntimeContext, code: typed): continuation
---@field sequence fun(first: continuation, second: continuation): continuation
return {}
