-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "continuation.lua"
---@class (exact) continuation
---@field kind string
---@field pretty_print fun(...)
continuation = {}
---@return boolean
function continuation:is_empty() end
---@return boolean
function continuation:is_frame() end
---@return any, typed
function continuation:unwrap_frame() end
---@return boolean, any, typed
function continuation:as_frame() end
---@return boolean
function continuation:is_sequence() end
---@return continuation, continuation
function continuation:unwrap_sequence() end
---@return boolean, continuation, continuation
function continuation:as_sequence() end
---@class (exact) continuationType:Type
---@field empty continuation
---@field frame fun(context:any, code:typed): continuation
---@field sequence fun(first:continuation, second:continuation): continuation
return {}
