-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "types.edgenotif"

---@class (exact) edgenotif: EnumValue
edgenotif = {}

---@return boolean
function edgenotif:is_Constrain() end
---@return integer left
---@return SubtypeRelation rel
---@return integer right
---@return integer shallowest_block
---@return constraintcause cause
function edgenotif:unwrap_Constrain() end
---@return boolean
---@return integer left
---@return SubtypeRelation rel
---@return integer right
---@return integer shallowest_block
---@return constraintcause cause
function edgenotif:as_Constrain() end
---@return boolean
function edgenotif:is_CallLeft() end
---@return integer left
---@return flex_value arg
---@return SubtypeRelation rel
---@return integer right
---@return integer shallowest_block
---@return constraintcause cause
function edgenotif:unwrap_CallLeft() end
---@return boolean
---@return integer left
---@return flex_value arg
---@return SubtypeRelation rel
---@return integer right
---@return integer shallowest_block
---@return constraintcause cause
function edgenotif:as_CallLeft() end
---@return boolean
function edgenotif:is_CallRight() end
---@return integer left
---@return SubtypeRelation rel
---@return integer right
---@return flex_value arg
---@return integer shallowest_block
---@return constraintcause cause
function edgenotif:unwrap_CallRight() end
---@return boolean
---@return integer left
---@return SubtypeRelation rel
---@return integer right
---@return flex_value arg
---@return integer shallowest_block
---@return constraintcause cause
function edgenotif:as_CallRight() end

---@class (exact) edgenotifType: EnumType
---@field define_enum fun(self: edgenotifType, name: string, variants: Variants): edgenotifType
---@field Constrain fun(left: integer, rel: SubtypeRelation, right: integer, shallowest_block: integer, cause: constraintcause): edgenotif
---@field CallLeft fun(left: integer, arg: flex_value, rel: SubtypeRelation, right: integer, shallowest_block: integer, cause: constraintcause): edgenotif
---@field CallRight fun(left: integer, rel: SubtypeRelation, right: integer, arg: flex_value, shallowest_block: integer, cause: constraintcause): edgenotif
return {}
