-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "effect_id.lua"

---@class (exact) effect_id: RecordValue
effect_id = {}

---@return table, SetValue
function effect_id:unwrap_effect_id() end

-- TODO: constructor annotation
---@class (exact) effect_idType: RecordType
return {}
