-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "types.effect_id"

---@class (exact) effect_id: RecordValue
effect_id = {}

---@return table
---@return SetValue<table>
function effect_id:unwrap_effect_id() end

-- TODO: constructor annotation
---@class (exact) effect_idType: RecordType
---@field define_record fun(self: effect_idType, kind: string, params_with_types: ParamsWithTypes): effect_idType
return {}
