-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "types.expression_goal"

---@class (exact) expression_goal: EnumValue
expression_goal = {}

---@return boolean
function expression_goal:is_infer() end
---@return nil
function expression_goal:unwrap_infer() end
---@return boolean
function expression_goal:as_infer() end
---@return boolean
function expression_goal:is_check() end
---@return flex_value goal_type
function expression_goal:unwrap_check() end
---@return boolean
---@return flex_value goal_type
function expression_goal:as_check() end
---@return boolean
function expression_goal:is_mechanism() end
---@return flex_value TODO
function expression_goal:unwrap_mechanism() end
---@return boolean
---@return flex_value TODO
function expression_goal:as_mechanism() end

---@class (exact) expression_goalType: EnumType
---@field define_enum fun(self: expression_goalType, name: string, variants: Variants): expression_goalType
---@field infer expression_goal
---@field check fun(goal_type: flex_value): expression_goal
---@field mechanism fun(TODO: flex_value): expression_goal
return {}
