-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "expression_goal.lua"

---@class (exact) expression_goal: EnumValue
expression_goal = {}

---@return boolean
function expression_goal:is_infer() end
---@return nil
function expression_goal:unwrap_infer() end
---@return boolean
function expression_goal:as_infer() end
---@return boolean
function expression_goal:is_check() end
---@return value
function expression_goal:unwrap_check() end
---@return boolean, value
function expression_goal:as_check() end
---@return boolean
function expression_goal:is_mechanism() end
---@return value
function expression_goal:unwrap_mechanism() end
---@return boolean, value
function expression_goal:as_mechanism() end

---@class (exact) expression_goalType: EnumType
---@field infer expression_goal
---@field check fun(goal_type: value): expression_goal
---@field mechanism fun(TODO: value): expression_goal
return {}
