-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "types.free"

---@class (exact) free: EnumValue
free = {}

---@return boolean
function free:is_metavariable() end
---@return Metavariable
function free:unwrap_metavariable() end
---@return boolean, Metavariable
function free:as_metavariable() end
---@return boolean
function free:is_placeholder() end
---@return number, placeholder_debug
function free:unwrap_placeholder() end
---@return boolean, number, placeholder_debug
function free:as_placeholder() end
---@return boolean
function free:is_unique() end
---@return table
function free:unwrap_unique() end
---@return boolean, table
function free:as_unique() end

---@class (exact) freeType: EnumType
---@field define_enum fun(self: freeType, name: string, variants: Variants): freeType
---@field metavariable fun(metavariable: Metavariable): free
---@field placeholder fun(index: number, debug: placeholder_debug): free
---@field unique fun(id: table): free
return {}
