-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "types.placeholder_debug"

---@class (exact) placeholder_debug: RecordValue
placeholder_debug = {}

---@return string
---@return Anchor
---@return Anchor
function placeholder_debug:unwrap_placeholder_debug() end

-- TODO: constructor annotation
---@class (exact) placeholder_debugType: RecordType
---@field define_record fun(self: placeholder_debugType, kind: string, params_with_types: ParamsWithTypes): placeholder_debugType
return {}
