-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "purity.lua"

---@class (exact) purity: EnumValue
purity = {}

---@return boolean
function purity:is_effectful() end
---@return nil
function purity:unwrap_effectful() end
---@return boolean
function purity:as_effectful() end
---@return boolean
function purity:is_pure() end
---@return nil
function purity:unwrap_pure() end
---@return boolean
function purity:as_pure() end

---@class (exact) purityType: EnumType
---@field define_enum fun(self: purityType, name: string, variants: Variants): purityType
---@field effectful purity
---@field pure purity
return {}
