-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "types.spanned_name"

---@class (exact) spanned_name: RecordValue
spanned_name = {}

---@return string
---@return Span
function spanned_name:unwrap_spanned_name() end

---@class (exact) spanned_nameType: RecordType
---@overload fun(name: string, name_span: Span): spanned_name
---@field define_record fun(self: spanned_nameType, kind: string, params_with_types: ParamsWithTypes): spanned_nameType
return {}
