-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "types.strict_continuation"

---@class (exact) strict_continuation: EnumValue
strict_continuation = {}

---@return boolean
function strict_continuation:is_empty() end
---@return nil
function strict_continuation:unwrap_empty() end
---@return boolean
function strict_continuation:as_empty() end
---@return boolean
function strict_continuation:is_frame() end
---@return StrictRuntimeContext context
---@return typed code
function strict_continuation:unwrap_frame() end
---@return boolean
---@return StrictRuntimeContext context
---@return typed code
function strict_continuation:as_frame() end
---@return boolean
function strict_continuation:is_sequence() end
---@return strict_continuation first
---@return strict_continuation second
function strict_continuation:unwrap_sequence() end
---@return boolean
---@return strict_continuation first
---@return strict_continuation second
function strict_continuation:as_sequence() end

---@class (exact) strict_continuationType: EnumType
---@field define_enum fun(self: strict_continuationType, name: string, variants: Variants): strict_continuationType
---@field empty strict_continuation
---@field frame fun(context: StrictRuntimeContext, code: typed): strict_continuation
---@field sequence fun(first: strict_continuation, second: strict_continuation): strict_continuation
return {}
