-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "types.stuck_continuation"

---@class (exact) stuck_continuation: EnumValue
stuck_continuation = {}

---@return boolean
function stuck_continuation:is_frame() end
---@return FlexRuntimeContext context
---@return typed code
function stuck_continuation:unwrap_frame() end
---@return boolean
---@return FlexRuntimeContext context
---@return typed code
function stuck_continuation:as_frame() end
---@return boolean
function stuck_continuation:is_sequence() end
---@return flex_continuation first
---@return flex_continuation second
function stuck_continuation:unwrap_sequence() end
---@return boolean
---@return flex_continuation first
---@return flex_continuation second
function stuck_continuation:as_sequence() end

---@class (exact) stuck_continuationType: EnumType
---@field define_enum fun(self: stuck_continuationType, name: string, variants: Variants): stuck_continuationType
---@field frame fun(context: FlexRuntimeContext, code: typed): stuck_continuation
---@field sequence fun(first: flex_continuation, second: flex_continuation): stuck_continuation
return {}
