-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "types.var_debug"

---@class (exact) var_debug: RecordValue
var_debug = {}

---@return string
---@return Anchor
function var_debug:unwrap_var_debug() end

-- TODO: constructor annotation
---@class (exact) var_debugType: RecordType
---@field define_record fun(self: var_debugType, kind: string, params_with_types: ParamsWithTypes): var_debugType
return {}
