-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "visibility.lua"
---@class (exact) visibility
---@field kind string
---@field pretty_print fun(...)
visibility = {}
---@return boolean
function visibility:is_explicit() end
---@return boolean
function visibility:is_implicit() end
---@class (exact) visibilityType:Type
---@field explicit visibility
---@field implicit visibility
return {}
